### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: Result is already complete

### ISSUE THREAD

**Issue by aaloise** [vert-x3/vertx-lang-groovy#117]
The following code works well until 4.0.0.Beta1 which uses Groovy 3.0.3. Starting with 4.0.0.Beta2, which uses Groovy 3.0.5, it started to fail:

```
Promise p = Promise.promise()
p.future().onSuccess { println it }
p.complete("Done with Groovy!!!")
```
```
Exception in thread "main" java.lang.IllegalStateException: Result is already complete
        at io.vertx.core.Promise.complete(Promise.java:67)
        at io.vertx.core.Promise$complete$1.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at org.example.MainGroovy.main(MainGroovy.groovy:17)
```

The bug doesn't happen whit Vertx 3.9. I tried with 3.9.5-SNAPSHOT, which is already using Groovy 3.0.7, and it is OK.

This is probably an issue with Groovy. I raised one that can be seen here https://issues.apache.org/jira/browse/GROOVY-9852. I opened this one here so we can track how things go.

**Comment by aaloise** [comment]
The issue was fixed in Groovy, but only for Groovy 4.x which is still in alpha phase. When Groovy 4.0 hits GA then it can be used in Vert.x 4 also, but I think it would be more apropriate to upgrade in Vert.x 4.1.

Meanwhile, a workaround to Groovy 3.x, and Vert.x 4,  is to use the following code :

```
Promise p = Promise.promise()
p.future().onSuccess({ println it } as io.vertx.core.Handler)
p.complete("Done with Groovy!!!")
```

**Comment by tsegismont** [comment]
Thanks for letting us know @aaloise
