### ISSUE TITLE
How to use Groovy Future?

### ISSUE THREAD

**Issue by thokari** [vert-x3/vertx-lang-groovy#28]
The Exception:
```
groovy.lang.MissingMethodException: No signature of method: io.vertx.groovy.core.Future.succeeded() is applicable for argument types: () values: []
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at de.thokari.vertx.registration.registration$_run_closure3$_closure12.doCall(registration.groovy:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at de.thokari.vertx.registration.registration$_comparePasswordAndGetPermissions_closure6$_closure16.doCall(registration.groovy:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DngMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:53)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:105)
	at com.sun.proxy.$Proxy13.handle(Unknown Source)
	at io.vertx.groovy.ext.sql.SQLConnection$2.handle(SQLConnection.groovy:94)
	at io.vertx.groovy.ext.sql.SQLConnection$2.handle(SQLConnection.groovy)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:135)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$null$14(ContextImpl.java:305)
	at io.vertx.core.impl.ContextImpl$$Lambda$26/1044635281.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(ContextImpl.java:335)
	at io.vertx.core.impl.ContextImpl$$Lambda$27/983610311.run(Unknown Source)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
```

The relevant code:

`cb(io.vertx.groovy.core.Future.failedFuture('Credentials do not match'))`

This however works:

```
vertx.executeBlocking({ future ->
    future.fail('Credentials do not match')
}, { res ->
    cb(res)
})
```

It works when dealing with an io.vertx.core.Future, but not io.vertx.groovy.core.Future.

**Comment by thokari** [comment]
It turns out I can actually just import / use io.vertx.core.Future. So it really is not a problem, I am just confused...

**Comment by vietj** [comment]
actually you are right , it should be here and it's not because it is inherited from AsyncResult, it should be there in 3.2.1 I think.

**Comment by thokari** [comment]
Awesome!

**Comment by vietj** [comment]
https://github.com/vert-x3/issues/issues/89
