### ISSUE TITLE
JsonSlupper to JsonObject not working

### ISSUE THREAD

**Issue by adpande** [vert-x3/vertx-lang-groovy#30]
Hi,

I am converting JsonSlurper to vertx JsonObject it is not working for complex json.

def slurper = new JsonSlurper()
def result = slurper.parseText('some complex json')
// result is a map instance.
JsonObject json = new JsonObject(result)

When i try to send this json object over eventbus. it gives error.
# 

java.lang.IllegalStateException: Illegal type in JsonObject: class java.math.BigDecimal
    at io.vertx.core.json.Json.checkAndCopy(Json.java:120) ~[flint-lib-0.1.0.0-all.jar:?]
    at io.vertx.core.json.JsonObject.copy(JsonObject.java:700) ~[flint-lib-0.1.0.0-all.jar:?]
    at io.vertx.core.json.Json.checkAndCopy(Json.java:107) ~[flint-lib-0.1.0.0-all.jar:?]
    at io.vertx.core.json.JsonObject.copy(JsonObject.java:700) ~[flint-lib-0.1.0.0-all.jar:?]
    at io.vertx.core.json.Json.checkAndCopy(Json.java:107) ~[flint-lib-0.1.0.0-all.jar:?]
    at io.vertx.core.json.JsonObject.copy(JsonObject.java:700) ~[flint-lib-0.1.0.0-all.jar:?]
    at io.vertx.core.json.Json.checkAndCopy(Json.java:99) ~[flint-lib-0.1.0.0-all.jar:?]
    at io.vertx.core.json.JsonObject.copy(JsonObject.java:700) ~[flint-lib-0.1.0.0-all.jar:?]
    at io.vertx.core.json.Json.checkAndCopy(Json.java:99) ~[flint-lib-0.1.0.0-all.jar:?]
    at io.vertx.core.json.JsonObject.copy(JsonObject.java:700) ~[flint-lib-0.1.0.0-all.jar:?]
#     at io.vertx.core.eventbus.impl.codecs.JsonObjectMessageCodec.transform(JsonObjectMessageCodec.java:49) ~[flint-lib-0.1.0.0-all.jar:?]

Thanks & Regards,
Abhishek

**Comment by pmlopes** [comment]
Cannot reproduce, for example:
```
    Map<String, Object> map = new HashMap<>();
    map.put("big", new BigDecimal(Long.MAX_VALUE).add(new BigDecimal(Long.MAX_VALUE)));

    JsonObject json = new JsonObject(map);
    System.out.println(map.get("big"));
```

Does not show your problem, please add a reproducer otherwise we cannot do anything with it.

**Comment by leosilvadev** [comment]
JsonSlurper does not offer support for BigDecimal, you should use toString() on it or use a Codec that supports it.
Currently I am using a codec and sending my events through the delegate (because groovy eventBus wraps your Map and transform it to a JsonObject/Array), so my codec is registered over the Groovy Map.
I don't know if it is the best solution but is what we're doing for now.
