### ISSUE TITLE
Issue with JsonObject when converting to Map

### ISSUE THREAD

**Issue by frangarcia** [vert-x3/vertx-lang-groovy#52]
Does the next piece code represent an issue for you?

```
@Grapes([
    @Grab(group='io.vertx', module='vertx-core', version='3.4.1'),    
    @Grab(group='io.vertx', module='vertx-lang-groovy', version='3.4.1')
])
import io.vertx.core.*
import io.vertx.core.json.*

JsonObject jo1 = new JsonObject()

assert "jo1 is a ${jo1?.class?.name}" == "jo1 is a io.vertx.core.json.JsonObject"

assert (jo1 as Map) instanceof Map


JsonObject jo2 = new JsonObject([:])

assert "jo2 is a ${jo2?.class?.name}" == "jo2 is a io.vertx.core.json.JsonObject"

assert (jo2 as Map) instanceof Map


JsonObject jo3 = new JsonObject([a:1])

assert "jo3 is a ${jo2?.class?.name}" == "jo3 is a io.vertx.core.json.JsonObject"

try {
    println (jo3 as Map)
} catch (Exception e) {
    assert true:"An exception has been thrown"
}
```

**Comment by vietj** [comment]
what's the problem here ?

**Comment by frangarcia** [comment]
An exception is thrown when doing

```
println (jo3 as Map)
```

but it does not happen when the json object is empty. Is that the expected behaviour?

**Comment by vietj** [comment]
JsonObject does not implement Map, so I guess that uses some kind of casting in Groovy ? what is the exception ?

**Comment by frangarcia** [comment]
groovy.lang.MissingMethodException: No signature of method: io.vertx.core.json.JsonObject.entrySet() is applicable for argument types: () values: []
Possible solutions: toSet(), intersect(java.lang.Iterable), encode(), every()
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:173)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at vertxgroovyerror.run(vertxgroovyerror.groovy:27)
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:263)
	at groovy.lang.GroovyShell.run(GroovyShell.java:518)
	at groovy.lang.GroovyShell.run(GroovyShell.java:497)
	at groovy.lang.GroovyShell.run(GroovyShell.java:170)
	at groovy.lang.GroovyShell$run$1.call(Unknown Source)
	at groovy.ui.Console$_runScriptImpl_closure16.doCall(Console.groovy:1005)
	at groovy.ui.Console$_runScriptImpl_closure16.doCall(Console.groovy)
	at sun.reflect.GeneratedMethodAccessor296.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:408)
	at groovy.lang.Closure.run(Closure.java:495)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vietj** [comment]
I think it is because JsonObject is not a Map, to work correctly, there should be a Groovy extension that converts a JsonObject as a Map

**Comment by frangarcia** [comment]
But how come it does not throw this exception for the variables jo1 or jo2? Both are also JsonObject variables. I don't get it.

**Comment by vietj** [comment]
I think it's because the map you get via dynamic programming is able to make the operation using reflection but when you print it (toString()), the actual toString() implementation looks for all the entries of the map and this method does not exists

**Comment by vietj** [comment]
I think you could contribute a Groovy extension for JsonObject so as Map is handled correctly

**Comment by frangarcia** [comment]
Sure! Can you send me any link/doc about how to develop a groovy extension? 

By the way, everything started because I am having some issues with JsonObject and Map in a vertx 3.4.1 I am writing and I saw this in the documentation (http://vertx.io/docs/vertx-core/groovy/):

> NOTE The configuration can also be a JsonObject object.

What does that really mean? Where a JsonObject is going to be returned and when a Map? That is a bit annoying to me.

**Comment by vietj** [comment]
I think that having a Groovy extension method (http://mrhaki.blogspot.fr/2013/01/groovy-goodness-adding-extra-methods.html)

```
public static Object as(JsonObject obj, Class type) {
  // Implement me
}
```

shall do the trick

**Comment by frangarcia** [comment]
What about the other question? It is really weird that depending on how I start the project (gradle run or shadowJar) 

`vertx.getOrCreateContext()?.config()`

is a Map (when starting up with gradle run) and a JsonObject (when starting up with the fat jar generated by shadowJar).

**Comment by jorgeuriarte** [comment]
Hi there @frangarcia; Did you get anywhere with this quest of yours? :)
We're suffering the same problem (JsonObject vs Map depending on launch mode) and it's becoming a hell of a problem... :(

**Comment by jorgeuriarte** [comment]
yup... .`mergeGroovyExtensionModules()` in the `shadowJar` configuration will make sure the groovy extensions are correctly included. I've been chasing a ghost, I think :)

**Comment by frangarcia** [comment]
Not really, but just in case it helps, we found this issue in a multi module project and the only solution we found was to put the dependency compile "io.vertx:vertx-lang-groovy:3.4.1" at the top.  Sorry not being more helpful.
