### ISSUE TITLE
Groovy: eventBus.send() with DeliveryOptions fails in 3.6.3

### ISSUE THREAD

**Issue by injecteer** [vert-x3/vertx-lang-groovy#75]
my Groovy code:

```
class GatewayVerticle extends AbstractVerticle {
  DeliveryOptions HOP_OPTS = new DeliveryOptions( sendTimeout:5000 )
  @Override
  void start() throws Exception {    
    vertx.eventBus().send( 'addr', [ aa:42 ], HOP_OPTS ){ println it }
  }
}

```
fails with

>  java.lang.IllegalArgumentException: No message codec for type: class java.util.LinkedHashMap at io.vertx.core.eventbus.impl.CodecManager.lookupCodec(CodecManager.java:101) at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.createMessage(ClusteredEventBus.java:180) at io.vertx.core.eventbus.impl.EventBusImpl.send(EventBusImpl.java:111)

If I ommit the setting sendTimeout it fails with the same exception.

The following line works just fine:
`
vertx.eventBus().send( 'gateway', [ aa:42 ] ){ doSomeStuff() }`

If I convert the map into JsonObject, it also works:
`
vertx.eventBus().send( 'addr', new JsonObject( aa:42 ), HOP_OPTS ){}`

See https://stackoverflow.com/questions/55415485/vertx-3-6-3-eventbus-send-with-deliveryoptions-fail for further discuccsion

**Comment by vietj** [comment]
can you try with current vertx 4.0.0-SNAPSHOT to have an idea

**Comment by injecteer** [comment]
what's the easiest way to install the snapshot with gradle? a specifig repository?

**Comment by vietj** [comment]
this ?

```
snapshotRepository(url: "https://oss.sonatype.org/content/repositories/snapshots/") {
        authentication(userName: ossrhUsername, password: ossrhPassword)
      }
```

**Comment by injecteer** [comment]
the code for 4.0.0-SNAPSHOT compiles but upon start the following exception pops up:

> java.lang.NoClassDefFoundError: io/vertx/codegen/annotations/DataObject
	at io.vertx.lang.groovy.VertxExtensionModule.asType(VertxExtensionModule.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
	at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:56)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:935)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:926)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:181)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.asType(ScriptBytecodeAdapter.java:604)
	at io.mozaiq.gateway.GatewayVerticle.<init>(GatewayVerticle.groovy)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.vertx.lang.groovy.GroovyVerticleFactory.createVerticle(GroovyVerticleFactory.java:91)
	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:232)
	at io.vertx.core.impl.DeploymentManager.lambda$null$0(DeploymentManager.java:189)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:174)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:68)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$3(ContextImpl.java:172)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.vertx.codegen.annotations.DataObject
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 31 common frames omitted

**Comment by injecteer** [comment]
the issue is still reproducible in 3.7.0

**Comment by vietj** [comment]
can you provide a reproducer project ?

**Comment by injecteer** [comment]
https://github.com/injecteer/sendRepro

**Comment by tsegismont** [comment]
Change `HOP_OPTS` initialization to:

```groovy
def HOP_OPTS = [sendTimeout: 5000]
```

And then it will work as expected. This is because the extension module defines a method that takes a `LinkHashMap` for options, not a `DeliveryOptions` instance:

```java
public static <T>io.vertx.core.eventbus.EventBus send(io.vertx.core.eventbus.EventBus j_receiver, java.lang.String address, java.lang.Object message, java.util.Map<String, Object> options, io.vertx.core.Handler<io.vertx.core.AsyncResult<io.vertx.core.eventbus.Message<java.lang.Object>>> replyHandler) {
  // ...
}
```

Consequently at runtime the extension method is not used and the message parameter not converted to `JsonObject`.

To me this is working as expected but then perhaps we could duplicate all extension methods (one with regular option class, the other with `LinkedHashMap`). Thoughts @vietj ?

**Comment by injecteer** [comment]
I tried it, and with `@TypeChecked` it brings up the exception:

> GatewayVerticle.groovy: 137: [Static type checking] - Cannot find matching method io.vertx.core.eventbus.EventBus#send(java.lang.String, java.util.Map <K extends java.lang.Object, V extends java.lang.Object>, java.lang.Object, groovy.lang.Closure). Please check if the declared type is correct and if the method exists.
 @ line 137, column 9.
           vertx.eventBus().send( id, body + REPLY, HOP_OPTS ){ AsyncResult rs ->
           ^

**Comment by tsegismont** [comment]
With Vert.x 3.9 and Vert.x 4, the way to go is:

```groovy
class GatewayVerticle extends AbstractVerticle {
  DeliveryOptions HOP_OPTS = new DeliveryOptions(sendTimeout: 5000)

  @Override
  void start() throws Exception {
    vertx.eventBus().request('addr', [aa: 42] as JsonObject, HOP_OPTS) {
      if (it.succeeded()) {
        println(it.result())
      } else {
        it.cause().printStackTrace()
      }
    }
  }
}
```
